/* 墨屿 · 可选 AI 人物档案助手 */
'use strict';
(() => {
  const $=(s,r=document)=>r.querySelector(s), esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const CONFIG_KEY='moyu.ai.config.v1', SESSION_KEY='moyu.ai.key.session.v1', LOCAL_KEY='moyu.ai.key.local.v1';
  const presets=[
    ['custom','自定义兼容接口','',''],
    ['openai-gpt41mini','OpenAI · GPT-4.1 mini','https://api.openai.com/v1','gpt-4.1-mini'],
    ['deepseek-v4-flash','DeepSeek · V4 Flash','https://api.deepseek.com','deepseek-v4-flash'],
    ['deepseek-v4-pro','DeepSeek · V4 Pro','https://api.deepseek.com','deepseek-v4-pro'],
    ['qwen-plus','通义千问 · Qwen Plus','https://dashscope.aliyuncs.com/compatible-mode/v1','qwen-plus'],
    ['qwen-max','通义千问 · Qwen 3.8 Max','https://dashscope.aliyuncs.com/compatible-mode/v1','qwen3.8-max'],
    ['glm-52','智谱 · GLM-5.2','https://open.bigmodel.cn/api/paas/v4','glm-5.2'],
    ['gemini-flash','Google · Gemini 3.7 Flash','https://generativelanguage.googleapis.com/v1beta/openai','gemini-3.7-flash']
  ];
  const fields={fullName:'全名',aliasesText:'小名/绰号/代号',age:'年龄/生日',gender:'性别/性取向',body:'身高/体型',appearance:'外貌特征',signature:'标志性特征',surfaceIdentity:'表面职业/身份',hiddenIdentity:'隐藏身份/真实身份',traits:'核心性格标签',strengths:'主要优点',flaws:'致命缺点/阴暗面',speechStyle:'语言风格',background:'出身与家庭',motivation:'核心动机',fear:'内在恐惧',trauma:'高光/创伤事件',coreRelations:'核心关系',relationAttitude:'对核心关系的态度',socialStatus:'社交地位',storyRole:'角色定位',conflict:'核心冲突',arc:'成长弧光',items:'随身物品',summary:'一句话概括角色'};
  const defaultPrompt='你是严谨的中文小说人物档案整理助手。请只依据提供的正文证据整理角色档案，不得把猜测写成事实，不得补造正文没有的信息。无法确定的字段输出空字符串。语言应简洁、具体，并保留矛盾和不确定性。关系描述必须指出对象。输出严格 JSON 对象，只包含指定字段，不要 Markdown、解释或代码块。';
  function config(){try{return{preset:'custom',endpoint:'https://api.openai.com/v1',model:'',prompt:defaultPrompt,...JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')}}catch{return{preset:'custom',endpoint:'https://api.openai.com/v1',model:'',prompt:defaultPrompt}}}
  function key(){return sessionStorage.getItem(SESSION_KEY)||localStorage.getItem(LOCAL_KEY)||''}
  function endpoint(v){const x=v.trim().replace(/\/$/,'');return /\/chat\/completions$/.test(x)?x:x+'/chat/completions'}
  function roleText(role){const names=[role.name].concat(role.alias||[]).filter(Boolean),parts=[];for(const v of window.Moyu.getProject().tree||[])for(const c of v.chapters||[]){const paras=(c.content||'').split(/\n\s*\n/).filter(t=>names.some(n=>n&&t.includes(n)));if(paras.length)parts.push('【'+v.title+' · '+c.title+'】\n'+paras.join('\n\n'))}return parts.join('\n\n').slice(0,30000)}
  function parseJSON(text){const clean=String(text||'').replace(/^\`\`\`(?:json)?\s*/i,'').replace(/\s*\`\`\`$/,'').trim(),data=JSON.parse(clean),out={};Object.keys(fields).forEach(k=>out[k]=typeof data[k]==='string'?data[k].trim():'');return out}
  async function request(messages,maxTokens=1800){const c=config(),k=key();if(!c.endpoint||!c.model||!k)throw new Error('请先填写接口地址、模型名和密钥');const res=await fetch(endpoint(c.endpoint),{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+k},body:JSON.stringify({model:c.model,messages,temperature:.2,max_tokens:maxTokens})});if(!res.ok){let msg='';try{msg=(await res.json()).error?.message||''}catch{}throw new Error(msg||'接口请求失败（HTTP '+res.status+'）')}const data=await res.json();return data.choices?.[0]?.message?.content||''}
  function modal(html,cls=''){const box=document.createElement('div');box.className='ai-mask '+cls;box.innerHTML='<section class="ai-dialog">'+html+'</section>';document.body.appendChild(box);box.addEventListener('click',e=>{if(e.target===box||e.target.closest('[data-ai-close]'))box.remove()});return box}
  function settings(){const c=config(),saved=!!localStorage.getItem(LOCAL_KEY),box=modal(`<header><div><small>可选功能</small><h2>大模型接口设置</h2></div><button data-ai-close>×</button></header><div class="ai-form"><div class="ai-warning"><b>纯前端直连提示</b><p>密钥会由当前浏览器直接发送给你填写的接口。默认仅保存在本次会话；不要在公共电脑勾选长期保存。</p></div><label>常用模型预设<select id="aiPreset">${presets.map(x=>`<option value="${x[0]}" ${c.preset===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><label>接口地址<input id="aiEndpoint" value="${esc(c.endpoint)}" placeholder="https://api.openai.com/v1"></label><label>模型名<input id="aiModel" value="${esc(c.model)}" placeholder="填写接口支持的模型名称"></label><label>API 密钥<input id="aiKey" type="password" value="${esc(key())}" autocomplete="off" placeholder="sk-…"></label><label class="ai-check"><input id="aiRemember" type="checkbox" ${saved?'checked':''}>长期保存在这台电脑的浏览器中</label><label>内置人物档案提示词<textarea id="aiPrompt">${esc(c.prompt)}</textarea></label><small class="ai-help">兼容采用 Chat Completions 格式的 OpenAI 兼容接口。部分服务商可能禁止浏览器跨域直连。</small><div id="aiStatus" class="ai-status"></div></div><footer><button data-ai-test>测试连接</button><button class="ai-primary" data-ai-save>保存设置</button></footer>`);
    const save=()=>{const next={preset:$('#aiPreset',box).value,endpoint:$('#aiEndpoint',box).value.trim(),model:$('#aiModel',box).value.trim(),prompt:$('#aiPrompt',box).value.trim()||defaultPrompt},k=$('#aiKey',box).value.trim(),remember=$('#aiRemember',box).checked;localStorage.setItem(CONFIG_KEY,JSON.stringify(next));sessionStorage.setItem(SESSION_KEY,k);if(remember)localStorage.setItem(LOCAL_KEY,k);else localStorage.removeItem(LOCAL_KEY)};
    $('#aiPreset',box).onchange=e=>{const p=presets.find(x=>x[0]===e.target.value);if(p&&p[0]!=='custom'){ $('#aiEndpoint',box).value=p[2];$('#aiModel',box).value=p[3]}};
    $('[data-ai-save]',box).onclick=()=>{save();$('#aiStatus',box).textContent='设置已保存';setTimeout(()=>box.remove(),500)};
    $('[data-ai-test]',box).onclick=async e=>{save();const st=$('#aiStatus',box);e.target.disabled=true;st.textContent='正在连接…';try{await request([{role:'user',content:'只回复 OK'}],8);st.textContent='连接成功'}catch(err){st.textContent='连接失败：'+err.message}finally{e.target.disabled=false}};
  }
  async function generate(name){const role=(window.Moyu.getProject().chars||[]).find(c=>c.name===name);if(!role)return;const evidence=roleText(role);if(!evidence)return alert('正文中还没有检索到这个角色的内容');if(!key()||!config().model){settings();return}const wait=modal('<div class="ai-loading"><span></span><h3>正在整理 '+esc(name)+' 的人物档案</h3><p>仅发送包含该角色姓名或别名的正文段落</p></div>','ai-wait');try{const schema=Object.keys(fields).reduce((o,k)=>(o[k]='',o),{}),content=await request([{role:'system',content:config().prompt},{role:'user',content:'角色：'+name+'\n别名：'+((role.alias||[]).join('、')||'无')+'\n已有档案：'+JSON.stringify(role.profile||{})+'\n\n请输出以下 JSON 结构：\n'+JSON.stringify(schema)+'\n\n正文证据：\n'+evidence}]);wait.remove();preview(role,parseJSON(content))}catch(err){wait.remove();alert('生成失败：'+err.message)}}
  function preview(role,draft){const old=role.profile||{},available=Object.keys(fields).filter(k=>draft[k]);const box=modal(`<header><div><small>AI 草稿 · 写入前确认</small><h2>${esc(role.name)}的人物档案</h2></div><button data-ai-close>×</button></header><div class="ai-review"><p>默认只勾选当前为空的字段。请核对正文后再写入。</p>${available.map(k=>`<label><input type="checkbox" data-ai-field="${k}" ${old[k]?'':'checked'}><span><b>${esc(fields[k])}${old[k]?'<i>已有内容</i>':''}</b><em>${esc(draft[k])}</em>${old[k]?`<small>当前：${esc(old[k])}</small>`:''}</span></label>`).join('')||'<div class="ws-empty">模型没有返回可用内容。</div>'}</div><footer><button data-ai-close>取消</button><button class="ai-primary" data-ai-apply>确认写入所选字段</button></footer>`);
    $('[data-ai-apply]',box).onclick=()=>{const next={...old};box.querySelectorAll('[data-ai-field]:checked').forEach(x=>next[x.dataset.aiField]=draft[x.dataset.aiField]);window.Moyu.updateCharacter(role.name,{profile:next});box.remove();window.MoyuWorkspace.openCharacter(role.name)};
  }
  const settingsBtn=document.createElement('button');settingsBtn.className='text-tool-btn';settingsBtn.id='btnAISettings';settingsBtn.textContent='AI 设置';settingsBtn.title='配置可选的大模型接口';const anchor=$('#btnWorkspace');anchor.parentNode.insertBefore(settingsBtn,anchor.nextSibling);settingsBtn.onclick=settings;
  function enhance(){const actions=$('.ws-pane-actions'),name=$('#wsRolePane h2')?.textContent;if(!actions||!name||actions.querySelector('[data-ai-generate]'))return;const b=document.createElement('button');b.dataset.aiGenerate='';b.textContent='AI 生成档案草稿';b.onclick=()=>generate(name);actions.prepend(b)}
  new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});enhance();
})();
