/* 墨屿 · 故事资料库 */
'use strict';
(() => {
  const $ = (s,r=document) => r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const clone=v=>JSON.parse(JSON.stringify(v));
  const P=()=>window.Moyu.getProject(), active=()=>window.Moyu.getActiveChapter&&window.Moyu.getActiveChapter();
  const HISTORY='moyu.writer.history.v2'; let captureTimer=null, currentRole=null, currentTab='characters';
  const profileFields=[
    ['身份档案',[['fullName','全名'],['aliasesText','小名/绰号/代号'],['age','年龄/生日'],['gender','性别/性取向'],['body','身高/体型'],['appearance','外貌特征'],['signature','标志性特征'],['surfaceIdentity','表面职业/身份'],['hiddenIdentity','隐藏身份/真实身份']]],
    ['性格特质',[['traits','核心性格标签'],['strengths','主要优点'],['flaws','致命缺点/阴暗面'],['speechStyle','语言风格']]],
    ['背景与动机',[['background','出身与家庭'],['motivation','核心动机'],['fear','内在恐惧'],['trauma','高光/创伤事件']]],
    ['人际关系',[['coreRelations','核心关系'],['relationAttitude','对核心关系的态度'],['socialStatus','社交地位']]],
    ['剧情功能与成长',[['storyRole','角色定位'],['conflict','核心冲突'],['arc','成长弧光']]],
    ['细节与判词',[['items','随身物品'],['summary','一句话概括角色']]]
  ];
  const shell=document.createElement('div'); shell.className='ws-shell'; shell.hidden=true; shell.innerHTML=`<div class="ws-mask"></div><section class="ws-dialog"><header><div><small>墨屿</small><strong id="wsTitle">故事资料库</strong></div><button id="wsClose">×</button></header><nav id="wsNav"></nav><main id="wsBody"></main></section>`; document.body.appendChild(shell);
  const body=$('#wsBody',shell), nav=$('#wsNav',shell), title=$('#wsTitle',shell);
  const selection=document.createElement('div'); selection.className='ws-selection'; selection.hidden=true; selection.innerHTML='<button data-sel="new">标记新角色</button><button data-sel="bind">绑定已有角色</button><button data-sel="search">检索角色证据</button>'; document.body.appendChild(selection);
  function open(t='characters'){shell.hidden=false; render(t)} function close(){shell.hidden=true} $('#wsClose',shell).onclick=close; $('.ws-mask',shell).onclick=close;
  const tabs=[['characters','人物档案'],['evidence','正文证据'],['relations','关系演化'],['checks','一致性检查'],['events','故事事件'],['foreshadows','伏笔管理']];
  function render(t){currentTab=t; nav.innerHTML=tabs.map(x=>`<button data-tab="${x[0]}" class="${t===x[0]?'active':''}">${x[1]}</button>`).join(''); if(t==='characters')renderCharacters(); if(t==='evidence')renderEvidence(); if(t==='relations')renderRelations(); if(t==='checks')renderChecks(); if(t==='events')renderEvents(); if(t==='foreshadows')renderForeshadows()}
  nav.onclick=e=>{const b=e.target.closest('[data-tab]');if(b)render(b.dataset.tab)};
  function chapters(){const out=[];(P().tree||[]).forEach(v=>(v.chapters||[]).forEach(c=>out.push({id:c.id,title:c.title,vol:v.title,text:c.content||''})));return out}
  function role(name){return(P().chars||[]).find(c=>c.name===name||(c.alias||[]).includes(name))}
  function roleNames(r){return[r.name].concat(r.alias||[]).filter(Boolean)}
  function paragraphs(){return chapters().flatMap(c=>c.text.split(/\n\s*\n/).map((text,i)=>({chapterId:c.id,title:c.title,vol:c.vol,text:text.trim(),index:i})).filter(x=>x.text))}
  function classify(text,others){if(/[“”「」『』"].*(说|问|答|喊|道|低声|笑道)/.test(text))return['dialogue','对话'];if(/(穿着|发色|瞳|眼睛|伤疤|胎记|身高|面容|长发|短发)/.test(text))return['appearance','外貌'];if(/(身份|是个|担任|来自|隶属|其实是|真实身份)/.test(text))return['identity','身份'];if(/(父亲|母亲|家人|童年|出生|故乡|家族|妹妹|哥哥)/.test(text))return['background','背景'];if(/(想要|必须|一定要|目标|害怕|恐惧|不愿失去)/.test(text))return['motivation','动机与恐惧'];if(/(怀表|戒指|剑|刀|信|项链|随身|遗物)/.test(text))return['item','物品'];if(others.length)return['relationship','人物关系'];return['event','关键事件']}
  function evidenceFor(r){const names=roleNames(r), chars=P().chars||[];return paragraphs().filter(p=>names.some(n=>n&&p.text.includes(n))).map(p=>{const term=names.find(n=>p.text.includes(n));const others=chars.filter(c=>c.name!==r.name&&roleNames(c).some(n=>n&&p.text.includes(n))).map(c=>c.name);const cat=classify(p.text,others);return{...p,term,others,category:cat[0],categoryName:cat[1],confidence:term===r.name?'明确':'别名匹配'}})}
  function renderCharacters(){title.textContent='人物档案'; const list=P().chars||[]; body.innerHTML=`<div class="ws-split"><aside class="ws-list"><button class="ws-primary" data-act="add-role">+ 新建角色</button>${list.map(c=>`<button data-role="${esc(c.name)}" class="${currentRole&&currentRole.name===c.name?'active':''}"><b>${esc(c.name||'未命名')}</b><span>${esc(c.tag||'配角')} · ${(c.evidence||[]).length}条证据</span></button>`).join('')}</aside><div class="ws-content" id="wsRolePane"></div></div>`; if(!currentRole&&list[0])currentRole=list[0]; if(currentRole&&!list.includes(currentRole))currentRole=list.find(c=>c.name===currentRole.name)||list[0]; renderProfile()}
  function renderProfile(){const pane=$('#wsRolePane',body);if(!pane)return;if(!currentRole){pane.innerHTML='<div class="ws-empty">新建或从正文标记一个角色。</div>';return}const p=currentRole.profile||{};pane.innerHTML=`<div class="ws-pane-head"><div><h2>${esc(currentRole.name)}</h2><p>${esc(currentRole.tag||'配角')} · ${(currentRole.evidence||[]).length} 条已归档证据</p></div><button data-act="role-evidence">查看正文证据</button></div><div class="ws-profile">${profileFields.map(g=>`<fieldset><legend>${g[0]}</legend>${g[1].map(f=>`<label>${f[1]}<textarea data-field="${f[0]}">${esc(f[0]==='fullName'?(p[f[0]]||currentRole.name):f[0]==='aliasesText'?(p[f[0]]||(currentRole.alias||[]).join('、')):(p[f[0]]||''))}</textarea></label>`).join('')}</fieldset>`).join('')}</div><button class="ws-primary" data-act="save-profile">保存人物档案</button>`}
  function renderEvidence(){title.textContent='正文证据';const list=P().chars||[];if(!currentRole)currentRole=list[0];if(!currentRole){body.innerHTML='<div class="ws-empty">请先创建角色。</div>';return}const hits=evidenceFor(currentRole), saved=currentRole.evidence||[];body.innerHTML=`<div class="ws-toolbar"><select id="wsEvidenceRole">${list.map(c=>`<option ${c===currentRole?'selected':''}>${esc(c.name)}</option>`).join('')}</select><span>${hits.length}条检索结果 / ${saved.length}条已归档</span></div><div class="ws-chips"><button data-filter="">全部</button>${[...new Set(hits.map(h=>h.category))].map(k=>`<button data-filter="${k}">${esc(hits.find(h=>h.category===k).categoryName)}</button>`).join('')}</div><div class="ws-evidence">${hits.map((h,i)=>{const done=saved.some(x=>x.chapterId===h.chapterId&&x.text===h.text);return`<article data-category="${h.category}"><header><b>${h.categoryName}</b><span>${h.confidence}</span></header><button data-chapter="${h.chapterId}"><strong>${esc(h.vol)} · ${esc(h.title)}</strong><p>${esc(h.text)}</p></button>${h.others.length?`<small>同段人物：${esc(h.others.join('、'))}</small>`:''}<button ${done?`data-unarchive="${i}"`:`data-archive="${i}"`}>${done?'取消归档':'归入人物档案'}</button></article>`}).join('')||'<div class="ws-empty">正文中没有出现该角色姓名或别名。</div>'}</div>`;body._hits=hits}
  function renderRelations(){title.textContent='关系演化';const rels=P().manualRels||[];body.innerHTML=`<div class="ws-toolbar"><span>关系可按章节划分阶段，并归档正文证据。</span><button class="ws-primary" data-act="add-rel">+ 新建关系</button></div><div class="ws-grid">${rels.map(r=>`<article class="ws-rel"><h3>${esc(r.a||r.source)} ${r.direction==='one-way'?'→':'↔'} ${esc(r.b||r.target)}</h3><p>${esc(r.type||'自定义')} · ${esc(r.desc||'暂无描述')}</p><h4>关系阶段</h4>${(r.stages||[]).map(s=>`<div class="ws-stage"><b>${esc(s.start||'开始')}—${esc(s.end||'至今')}</b><span>${esc(s.type||'未定义')}：${esc(s.note||'')}</span></div>`).join('')||'<small>尚未记录阶段</small>'}<button data-rel-stage="${r.id}">+ 添加阶段</button><h4>关系证据 ${(r.evidence||[]).length} 条</h4><button data-rel-evidence="${r.id}">从共同正文中选择证据</button></article>`).join('')||'<div class="ws-empty">请先在人物关系网中建立关系。</div>'}</div>`}
  function runChecks(){const issues=[],p=P(),chs=chapters();(p.chars||[]).forEach(c=>{if(!c.name)issues.push(['角色','存在未命名角色']);if(!(c.alias||[]).length)issues.push([c.name,'尚未设置别名']);if(!(c.profile||{}).motivation)issues.push([c.name,'缺少核心动机']);if(!(c.profile||{}).fear)issues.push([c.name,'缺少内在恐惧']);if(c.status==='死亡'){chs.forEach(ch=>{if(ch.text.includes(c.name)&&(!c.deathChapter||ch.id!==c.deathChapter))issues.push([c.name,`死亡状态人物在《${ch.title}》出现，请确认时间顺序`])})}});(p.manualRels||[]).forEach(r=>{if(!r.type||r.type==='自定义')issues.push([`${r.a||r.source}—${r.b||r.target}`,'关系类型尚未明确']);if(!(r.evidence||[]).length)issues.push([`${r.a||r.source}—${r.b||r.target}`,'关系没有正文证据'])});return issues}
  function renderChecks(){title.textContent='人物一致性检查';const issues=runChecks();body.innerHTML=`<div class="ws-toolbar"><span>规则检查只提出疑点，不自动修改设定。</span><button data-act="rerun">重新检查</button></div><div class="ws-checks">${issues.map(x=>`<article><b>${esc(x[0])}</b><p>${esc(x[1])}</p></article>`).join('')||'<div class="ws-empty">没有发现规则层面的明显疑点。</div>'}</div>`}
  function renderEvents(){title.textContent='故事事件轴';const events=P().storyEvents||[];body.innerHTML=`<div class="ws-toolbar"><span>记录事件、参与人物及其对关系的影响。</span><button class="ws-primary" data-act="add-event">+ 新建事件</button></div><div class="ws-timeline">${events.map(e=>`<article><header><b>${esc(e.title)}</b><span>${esc(e.chapterTitle||'未绑定章节')}</span></header><p>${esc(e.summary||'')}</p><small>人物：${esc((e.characters||[]).join('、')||'未填写')} · 地点：${esc(e.location||'未填写')}</small><button data-del-event="${e.id}">删除</button></article>`).join('')||'<div class="ws-empty">尚未记录故事事件。</div>'}</div>`}
  function renderForeshadows(){title.textContent='伏笔管理';const list=P().foreshadows||[];body.innerHTML=`<div class="ws-toolbar"><span>跟踪伏笔的埋设、推进和回收。</span><button class="ws-primary" data-act="add-foreshadow">+ 新建伏笔</button></div><div class="ws-grid">${list.map(f=>`<article><header><b>${esc(f.title)}</b><span class="ws-status ${f.status}">${esc(f.status||'新伏笔')}</span></header><p>${esc(f.note||'')}</p><small>埋设：${esc(f.plantChapter||'未设置')} · 计划回收：${esc(f.payoffChapter||'未设置')}</small><select data-foreshadow-status="${f.id}"><option>新伏笔</option><option>已推进</option><option>已回收</option><option>废弃</option></select><button data-del-foreshadow="${f.id}">删除</button></article>`).join('')||'<div class="ws-empty">尚未记录伏笔。</div>'}</div>`;$$('[data-foreshadow-status]',body).forEach(s=>s.value=list.find(f=>f.id===s.dataset.foreshadowStatus).status||'新伏笔')}
  function promptText(label,def=''){return new Promise(resolve=>{const box=document.createElement('div');box.className='ws-ask';box.innerHTML=`<div><label>${esc(label).replace(/\n/g,'<br>')}<input value="${esc(def)}"></label><footer><button data-cancel>取消</button><button class="ws-primary" data-ok>确定</button></footer></div>`;document.body.appendChild(box);const input=$('input',box);input.focus();input.select();const done=v=>{box.remove();resolve(v)};$('[data-cancel]',box).onclick=()=>done(null);$('[data-ok]',box).onclick=()=>done(input.value.trim());input.onkeydown=e=>{if(e.key==='Enter')done(input.value.trim());if(e.key==='Escape')done(null)}})}
  body.onclick=async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.role){currentRole=role(b.dataset.role);renderCharacters();return}if(b.dataset.act==='add-role'){const n=await promptText('角色名');if(n){window.Moyu.addCharacter(n);currentRole=role(n);renderCharacters()}return}if(b.dataset.act==='save-profile'){const p={};$$('[data-field]',body).forEach(x=>p[x.dataset.field]=x.value.trim());const aliases=(p.aliasesText||'').split(/[,，、]/).map(x=>x.trim()).filter(Boolean);window.Moyu.updateCharacter(currentRole.name,{profile:p,alias:aliases});currentRole.profile=p;currentRole.alias=aliases;b.textContent='已保存';return}if(b.dataset.act==='role-evidence'){render('evidence');return}if(b.dataset.unarchive!=null){const h=body._hits[+b.dataset.unarchive],list=(currentRole.evidence||[]).filter(x=>!(x.chapterId===h.chapterId&&x.text===h.text));window.Moyu.updateCharacter(currentRole.name,{evidence:list});currentRole.evidence=list;renderEvidence();return}if(b.dataset.archive!=null){const h=body._hits[+b.dataset.archive],list=(currentRole.evidence||[]).slice();if(!list.some(x=>x.chapterId===h.chapterId&&x.text===h.text))list.push({...h,id:uid(),createdAt:Date.now()});window.Moyu.updateCharacter(currentRole.name,{evidence:list});currentRole.evidence=list;b.disabled=true;b.textContent='已归档';return}if(b.dataset.chapter){window.Moyu.openChapter(b.dataset.chapter);close();return}if(b.dataset.act==='add-rel'){const a=await promptText('人物A');if(a===null)return;const z=await promptText('人物B');if(!z)return;const type=await promptText('关系类型','盟友')||'自定义';window.Moyu.addManualRel({id:uid(),a,b:z,type,direction:'two-way',desc:'',weight:3,stages:[],evidence:[]});renderRelations();return}if(b.dataset.relStage){const r=(P().manualRels||[]).find(x=>x.id===b.dataset.relStage);const type=await promptText('该阶段的关系','盟友');if(type===null)return;const start=await promptText('开始章节','');const end=await promptText('结束章节（留空表示至今）','');const note=await promptText('变化原因','');r.stages=(r.stages||[]).concat({id:uid(),type,start,end,note});window.Moyu.updateManualRel(r.id,{stages:r.stages});renderRelations();return}if(b.dataset.relEvidence){await archiveRelationEvidence(b.dataset.relEvidence);return}if(b.dataset.act==='rerun'){renderChecks();return}if(b.dataset.act==='add-event'){await addEvent();return}if(b.dataset.delEvent){trash('event',(P().storyEvents||[]).find(x=>x.id===b.dataset.delEvent));P().storyEvents=P().storyEvents.filter(x=>x.id!==b.dataset.delEvent);window.Moyu.touch();renderEvents();return}if(b.dataset.act==='add-foreshadow'){await addForeshadow();return}if(b.dataset.delForeshadow){trash('foreshadow',P().foreshadows.find(x=>x.id===b.dataset.delForeshadow));P().foreshadows=P().foreshadows.filter(x=>x.id!==b.dataset.delForeshadow);window.Moyu.touch();renderForeshadows()}}
  body.onchange=e=>{if(e.target.id==='wsEvidenceRole'){currentRole=role(e.target.value);renderEvidence()}if(e.target.dataset.foreshadowStatus){const f=P().foreshadows.find(x=>x.id===e.target.dataset.foreshadowStatus);f.status=e.target.value;window.Moyu.touch()}}
  body.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f)$$('.ws-evidence article',body).forEach(x=>x.hidden=!!f.dataset.filter&&x.dataset.category!==f.dataset.filter)})
  async function archiveRelationEvidence(id){const r=P().manualRels.find(x=>x.id===id),a=role(r.a||r.source),z=role(r.b||r.target);if(!a||!z)return alert('关系两端人物必须存在');const hits=paragraphs().filter(p=>roleNames(a).some(n=>p.text.includes(n))&&roleNames(z).some(n=>p.text.includes(n)));if(!hits.length)return alert('正文中没有两人共同出现的段落');const choices=hits.map((h,i)=>`${i+1}. ${h.title}：${h.text.slice(0,50)}`).join('\n');const n=+(await promptText(`输入要归档的证据序号：\n${choices}`,'1')||0)-1;if(!hits[n])return;r.evidence=(r.evidence||[]).concat({...hits[n],id:uid(),createdAt:Date.now()});window.Moyu.updateManualRel(r.id,{evidence:r.evidence});renderRelations()}
  async function addEvent(){const t=await promptText('事件名称');if(!t)return;const ac=active(),summary=await promptText('事件经过','')||'',characters=(await promptText('参与人物（顿号分隔）','')||'').split(/[、,，]/).filter(Boolean),location=await promptText('地点','')||'';P().storyEvents.push({id:uid(),title:t,summary,characters,location,chapterId:ac&&ac.ch.id,chapterTitle:ac&&ac.ch.title,createdAt:Date.now()});window.Moyu.touch();renderEvents()}
  async function addForeshadow(){const t=await promptText('伏笔名称');if(!t)return;const ac=active(),note=await promptText('伏笔内容','')||'',payoffChapter=await promptText('预计回收章节','')||'';P().foreshadows.push({id:uid(),title:t,note,status:'新伏笔',plantChapter:ac&&ac.ch.title,payoffChapter,createdAt:Date.now()});window.Moyu.touch();renderForeshadows()}
  function histories(){try{return JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{return[]}}
  function capture(label='自动快照'){const p=P(),all=histories(),last=all[0];if(last&&last.projectId===p.id&&JSON.stringify(last.data)===JSON.stringify(p))return;all.unshift({id:uid(),projectId:p.id,label,createdAt:Date.now(),data:clone(p)});localStorage.setItem(HISTORY,JSON.stringify(all.slice(0,30)))}
  function captureSoon(){clearTimeout(captureTimer);captureTimer=setTimeout(()=>capture(),30000)}
  function showHistory(){capture('打开历史前');const list=histories().filter(x=>x.projectId===P().id);showSimple('历史版本',`<button class="ws-primary" data-history-new>立即创建快照</button>${list.map(x=>`<article><b>${esc(x.label)}</b><span>${new Date(x.createdAt).toLocaleString()}</span><button data-history-restore="${x.id}">恢复此版本</button></article>`).join('')||'<div class="ws-empty">暂无历史版本。</div>'}`)}
  function trash(type,data,meta={}){if(!data)return;P().trash.push({id:uid(),type,data:clone(data),meta,deletedAt:Date.now()});window.Moyu.touch()}
  function showTrash(){const list=P().trash||[];showSimple('回收站',list.map(x=>`<article><b>${esc(({chapter:'章节',volume:'分卷',character:'角色',relation:'关系',event:'事件',foreshadow:'伏笔'})[x.type]||x.type)}：${esc(x.data.title||x.data.name||x.data.type||'未命名')}</b><span>${new Date(x.deletedAt).toLocaleString()}</span><button data-trash-restore="${x.id}">恢复</button></article>`).join('')||'<div class="ws-empty">回收站为空。</div>')}
  function showSimple(t,html){shell.hidden=false;title.textContent=t;nav.innerHTML='';body.innerHTML=`<div class="ws-simple">${html}</div>`}
  shell.addEventListener('click',e=>{let b=e.target.closest('[data-history-new],[data-history-restore],[data-trash-restore]');if(!b)return;if(b.hasAttribute('data-history-new')){capture('手动快照');showHistory()}if(b.dataset.historyRestore){const h=histories().find(x=>x.id===b.dataset.historyRestore);if(h&&confirm('恢复后当前版本会先保存为快照，确定继续？')){capture('恢复前快照');const p=P();Object.keys(p).forEach(k=>delete p[k]);Object.assign(p,clone(h.data));window.Moyu.refresh();close()}}if(b.dataset.trashRestore){restoreTrash(b.dataset.trashRestore);showTrash()}})
  function restoreTrash(id){const p=P(),i=p.trash.findIndex(x=>x.id===id);if(i<0)return;const x=p.trash[i];if(x.type==='chapter'){const v=p.tree.find(v=>v.id===x.meta.volumeId)||p.tree[0];v&&v.chapters.push(x.data)}if(x.type==='volume')p.tree.push(x.data);if(x.type==='character')p.chars.push(x.data);if(x.type==='relation')p.manualRels.push(x.data);if(x.type==='event')p.storyEvents.push(x.data);if(x.type==='foreshadow')p.foreshadows.push(x.data);p.trash.splice(i,1);window.Moyu.refresh()}
  function addCardButtons(){if(!document.querySelector('.panel-tabs button.active[data-tab="chars"]'))return;$$('#panelBody .card').forEach(card=>{if(card.querySelector('[data-ws-profile]'))return;const id=card.dataset.id,c=P().chars.find(x=>x.id===id),actions=$('.card-actions',card);if(!c||!actions)return;const b=document.createElement('button');b.className='link-btn';b.dataset.wsProfile='';b.textContent=`人物档案 · ${(c.evidence||[]).length}条证据`;b.onclick=()=>openCharacter(c.name);actions.prepend(b)})}
  new MutationObserver(addCardButtons).observe($('#panelBody'),{childList:true,subtree:true});
  const editor=$('#editor');let picked=null;function showSelection(e){const a=editor.selectionStart,b=editor.selectionEnd,text=editor.value.slice(a,b).trim();if(!text||text.length>24){selection.hidden=true;return}picked={text,start:a,end:b,chapter:active()};const r=editor.getBoundingClientRect();selection.style.left=Math.min(innerWidth-310,Math.max(8,e&&e.clientX||r.left+80))+'px';selection.style.top=Math.max(55,(e&&e.clientY||r.top)-42)+'px';selection.hidden=false}
  editor.addEventListener('mouseup',e=>setTimeout(()=>showSelection(e)));selection.onclick=async e=>{const a=e.target.closest('[data-sel]');if(!a||!picked)return;if(a.dataset.sel==='new'){const n=await promptText('角色名',picked.text);if(n){window.Moyu.addCharacter(n);window.Moyu.saveCharacterAnnotation({id:uid(),characterName:n,text:picked.text,chapterId:picked.chapter&&picked.chapter.ch.id,start:picked.start,end:picked.end,createdAt:Date.now()});currentRole=role(n);open('evidence')}}if(a.dataset.sel==='bind'){const names=(P().chars||[]).map(c=>c.name).join('、');const n=await promptText(`绑定到哪个角色？\n${names}`);const r=role(n);if(r){if(picked.text!==r.name&&!r.alias.includes(picked.text)){r.alias.push(picked.text);window.Moyu.updateCharacter(r.name,{alias:r.alias})}window.Moyu.saveCharacterAnnotation({id:uid(),characterName:r.name,text:picked.text,chapterId:picked.chapter&&picked.chapter.ch.id,start:picked.start,end:picked.end,createdAt:Date.now()});currentRole=r;open('evidence')}}if(a.dataset.sel==='search'){const r=role(picked.text);if(r){currentRole=r;open('evidence')}else alert('请先标记或绑定这个角色')}selection.hidden=true}
  document.addEventListener('mousedown',e=>{if(!e.target.closest('.ws-selection')&&e.target!==editor)selection.hidden=true});
  function openCharacter(name){currentRole=role(name);open('characters')}
  $('#btnWorkspace').onclick=()=>open('characters');$('#btnHistory').onclick=showHistory;$('#btnTrash').onclick=showTrash;
  window.MoyuWorkspace={open,openCharacter,captureSoon,capture,trash,ask:promptText}; capture('功能升级初始快照'); addCardButtons();
})();